<h1><?php echo $this->poll->question; ?></h1>

<table border="1">
    <?php foreach ( $this->options as $option ): ?>
    <tr>
        <td><?php echo $option->name ?></td>
        <td><?php echo $option->number_votes ?></td>
        <td><?php echo $this->tag->linkTo( "poll/vote/" . $option->id, "Rösta" ); ?></td>
    </tr>
    <?php endforeach; ?>
</table>

<p>
    <?php echo $this->tag->linkTo( "poll", "Gå tillbaka" ); ?> -
    <?php echo $this->tag->linkTo( "poll/add/" . $this->poll->id, "Lägg till alternativ" ); ?>
</p>
